<a href="https://colab.research.google.com/github/Rishabhjain2109/deeplearning/blob/main/keras_tuner_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import numpy as np
import pandas as pd

In [68]:
df=pd.read_csv('diabetes.csv')

In [69]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [70]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [71]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [72]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [73]:
X=scaler.fit_transform(X)

In [74]:
X.shape

(768, 8)

In [75]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [76]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [77]:
model=Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [78]:
model.fit(X_train,y_train,batch_size=32,epochs=10,validation_data=(X_test,y_test))

Epoch 1/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.4104 - loss: 0.7537 - val_accuracy: 0.5974 - val_loss: 0.6985
Epoch 2/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5456 - loss: 0.6955 - val_accuracy: 0.6883 - val_loss: 0.6500
Epoch 3/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6401 - loss: 0.6504 - val_accuracy: 0.7273 - val_loss: 0.6100
Epoch 4/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6922 - loss: 0.6154 - val_accuracy: 0.7273 - val_loss: 0.5783
Epoch 5/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7150 - loss: 0.5856 - val_accuracy: 0.7468 - val_loss: 0.5545
Epoch 6/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5626 - val_accuracy: 0.7597 - val_loss: 0.5340
Epoch 7/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7394 - loss: 0.5436 - val_accuracy: 0.7792 - val_loss: 0.5185
Epoch 8/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7410 - loss: 0.5273 - val_accuracy: 0.7792 - val_loss: 0.5059
Epoch 9/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7443 - loss: 0.5138 - val_accuracy: 0.7662 - val_loss: 0.4948
Epoch 10/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5027 - val_accuracy: 0.7662 - val_loss: 0.4863

In [79]:
import kerastuner as kt

In [80]:
# def build_model(hp):
#   model=Sequential()
#   model.add(Dense(32,activation='relu',input_dim=8))
#   model.add(Dense(1,activation='sigmoid'))
#   optimizer=hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta'])
#   model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
#   return model

In [81]:
#tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5)

In [82]:
#tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [83]:
#tuner.get_best_hyperparameters()[0].values

In [84]:
#model=tuner.get_best_models(num_models=1)[0]

In [85]:
#model.summary()

In [86]:
#model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

In [87]:
# def build_model(hp):
#   model=Sequential()
#   units=hp.Int('units',min_value=8,max_value=128,step=5)
#   model.add(Dense(units=units,activation='relu',input_dim=8))
#   model.add(Dense(1,activation='sigmoid'))
#   model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
#   return model

In [88]:
#tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5,directory='mydir')

In [89]:
#tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [90]:
#tuner.get_best_hyperparameters()[0].values

In [91]:
#model=tuner.get_best_models(num_models=1)[0]

In [92]:
#model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

In [99]:
def build_model(hp):
  model=Sequential()
  model.add(Dense(78,activation='relu',input_dim=8))
  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    model.add(Dense(78,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [100]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5,directory='mkdirdir',project_name='keras_tuner_layers')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [101]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 06s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 23s

In [102]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 9}

In [103]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 46 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [105]:
model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - accuracy: 0.7818 - loss: 0.4657 - val_accuracy: 0.8247 - val_loss: 0.4533
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4323 - val_accuracy: 0.8117 - val_loss: 0.4522
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7899 - loss: 0.4313 - val_accuracy: 0.7987 - val_loss: 0.4436
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8111 - loss: 0.4235 - val_accuracy: 0.7922 - val_loss: 0.4505
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8306 - loss: 0.4039 - val_accuracy: 0.8182 - val_loss: 0.4434
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8029 - loss: 0.4295 - val_accuracy: 0.8052 - val_loss: 0.4508
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8257 - loss: 0.3920 - val_accuracy: 0.8247 - val_loss: 0.4592
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8339 - loss: 0.3747 - val_accuracy: 0.8117 - val_loss: 0.4547
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8436 - loss: 0.3682 - val_accuracy: 0.7857 - val_loss: 0.4768
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8518 - loss: 0.3516 - val_accuracy: 0.7597 - val_loss: 0.5492
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8404 - loss: 0.3506 - val_accuracy: 0.7922 - val_loss: 0.4963
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8746 - loss: 0.3114 - val_accuracy: 0.7857 - val_loss: 0.5205
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8795 - loss: 0.3020 - val_accuracy: 0.7857 - val_loss: 0.5466
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.2743 - val_accuracy: 0.7338 - val_loss: 0.6338
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8534 - loss: 0.3215 - val_accuracy: 0.7597 - val_loss: 0.5127
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9072 - loss: 0.2434 - val_accuracy: 0.7403 - val_loss: 0.6808
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.2557 - val_accuracy: 0.7662 - val_loss: 0.6854
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9137 - loss: 0.2441 - val_accuracy: 0.6883 - val_loss: 0.7109
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9121 - loss: 0.2315 - val_accuracy: 0.7792 - val_loss: 0.7050
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9235 - loss: 0.1991 - val_accuracy: 0.7403 - val_loss: 0.8467
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1831 - val_accuracy: 0.7208 - val_loss: 0.9938
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9235 - loss: 0.2053 - val_accuracy: 0.7532 - val_loss: 0.7626
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9381 - loss: 0.1789 - val_accuracy: 0.6948 - val_loss: 0.8955
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1710 - val_accuracy: 0.7208 - val_loss: 0.8224
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9511 - loss: 0.1295 - val_accuracy: 0.7662 - val_loss: 1.0248
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9609 - loss: 0.0985 - val_accuracy: 0.7273 - val_loss: 1.2027
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9397 - loss: 0.1371 - val_accuracy: 0.6883 - val_loss: 1.1645
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9577 - loss: 0.1255 - val_accuracy: 0.7013 - val_loss: 1.0335
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9674 - loss: 0.1178 - val_accuracy: 0.7403 - val_loss: 1.1697
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9544 - loss: 0.1181 - val_accuracy: 0.7403 - val_loss: 1.3390
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9691 - loss: 0.0903 - val_accuracy: 0.7792 - val_loss: 1.1032
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0751 - val_accuracy: 0.7078 - val_loss: 1.4807
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0688 - val_accuracy: 0.6558 - val_loss: 1.4649
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9593 - loss: 0.1043 - val_accuracy: 0.7532 - val_loss: 1.1780
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0611 - val_accuracy: 0.6948 - val_loss: 1.6643
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0503 - val_accuracy: 0.7208 - val_loss: 1.6209
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9235 - loss: 0.2189 - val_accuracy: 0.7143 - val_loss: 0.9288
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2399 - val_accuracy: 0.7532 - val_loss: 0.7608
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9642 - loss: 0.1059 - val_accuracy: 0.7468 - val_loss: 1.1783
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0440 - val_accuracy: 0.7143 - val_loss: 1.7844
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.1126 - val_accuracy: 0.7208 - val_loss: 1.4491
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9691 - loss: 0.0982 - val_accuracy: 0.7403 - val_loss: 1.1478
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9886 - loss: 0.0404 - val_accuracy: 0.7468 - val_loss: 1.4852
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0252 - val_accuracy: 0.7338 - val_loss: 2.1228
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9772 - loss: 0.0650 - val_accuracy: 0.7338 - val_loss: 1.6294
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9739 - loss: 0.0792 - val_accuracy: 0.7532 - val_loss: 1.1809
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9691 - loss: 0.0790 - val_accuracy: 0.7532 - val_loss: 1.2840
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0291 - val_accuracy: 0.7662 - val_loss: 1.5425
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9935 - loss: 0.0441 - val_accuracy: 0.7273 - val_loss: 1.3740
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9902 - loss: 0.0272 - val_accuracy: 0.7273 - val_loss: 1.5837
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0265 - val_accuracy: 0.7532 - val_loss: 1.7060
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9951 - loss: 0.0167 - val_accuracy: 0.7468 - val_loss: 1.8360
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9886 - loss: 0.0392 - val_accuracy: 0.7532 - val_loss: 1.9931
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9772 - loss: 0.0744 - val_accuracy: 0.7338 - val_loss: 1.5054
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9853 - loss: 0.0537 - val_accuracy: 0.7468 - val_loss: 1.4667
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9625 - loss: 0.1044 - val_accuracy: 0.7338 - val_loss: 1.0092
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9723 - loss: 0.0752 - val_accuracy: 0.7468 - val_loss: 1.1294
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0447 - val_accuracy: 0.7532 - val_loss: 1.4145
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0236 - val_accuracy: 0.7532 - val_loss: 1.5491
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0207 - val_accuracy: 0.7403 - val_loss: 1.7396
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9951 - loss: 0.0247 - val_accuracy: 0.7208 - val_loss: 1.8456
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9935 - loss: 0.0248 - val_accuracy: 0.7403 - val_loss: 1.8270
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0116 - val_accuracy: 0.7468 - val_loss: 1.8675
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0140 - val_accuracy: 0.7338 - val_loss: 2.1047
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0071 - val_accuracy: 0.7468 - val_loss: 2.2293
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0030 - val_accuracy: 0.7273 - val_loss: 2.4961
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0093 - val_accuracy: 0.7468 - val_loss: 2.4067
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9951 - loss: 0.0239 - val_accuracy: 0.7403 - val_loss: 2.0119
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9951 - loss: 0.0113 - val_accuracy: 0.7338 - val_loss: 2.1682
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0097 - val_accuracy: 0.7338 - val_loss: 2.3229
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.7403 - val_loss: 2.5192
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 7.6930e-04 - val_accuracy: 0.7403 - val_loss: 2.7338
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 3.5000e-04 - val_accuracy: 0.7403 - val_loss: 2.8458
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 2.3131e-04 - val_accuracy: 0.7403 - val_loss: 2.9393
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 1.8441e-04 - val_accuracy: 0.7403 - val_loss: 3.0399
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 1.3869e-04 - val_accuracy: 0.7403 - val_loss: 3.1706
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 1.0738e-04 - val_accuracy: 0.7403 - val_loss: 3.2662
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 8.8161e-05 - val_accuracy: 0.7403 - val_loss: 3.3516
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 7.5243e-05 - val_accuracy: 0.7403 - val_loss: 3.4295
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 6.4061e-05 - val_accuracy: 0.7403 - val_loss: 3.4924
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 5.6494e-05 - val_accuracy: 0.7403 - val_loss: 3.5525
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 4.9903e-05 - val_accuracy: 0.7403 - val_loss: 3.6023
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 4.5016e-05 - val_accuracy: 0.7403 - val_loss: 3.6597
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 4.0537e-05 - val_accuracy: 0.7403 - val_loss: 3.7067
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 3.6670e-05 - val_accuracy: 0.7403 - val_loss: 3.7442
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 3.3831e-05 - val_accuracy: 0.7468 - val_loss: 3.7846
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 3.1300e-05 - val_accuracy: 0.7468 - val_loss: 3.8202
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 2.8710e-05 - val_accuracy: 0.7468 - val_loss: 3.8614
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 2.6872e-05 - val_accuracy: 0.7468 - val_loss: 3.9041
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 2.4904e-05 - val_accuracy: 0.7468 - val_loss: 3.9323
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 2.3244e-05 - val_accuracy: 0.7468 - val_loss: 3.9667
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 2.1788e-05 - val_accuracy: 0.7468 - val_loss: 4.0021
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 2.0389e-05 - val_accuracy: 0.7468 - val_loss: 4.0284
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.9343e-05 - val_accuracy: 0.7532 - val_loss: 4.0547